### ISSUE TITLE
Speech recognition failure after update

### ISSUE THREAD

**Issue by egeerts** [tue-robotics/dragonfly_speech_recognition#7]
Speech recognition does not work anymore in the GPSR and the person_recognition challenges.

I've looked into the problem and my conclusion is that if there is more than one key-value combination in the choices-dictionary, it results into a key-error. 

The most likely reason to this new problem is that Max updated all the packages with: 
tue-app-get update (or something like this...?!) causing an update for dragonfly. 
There has nothing changed with the files itself and in the wrapper for dragonfly. 

Rein, could you have a look at this on Tuesday since it is very important that it works again. Perhaps in the wrapper we could change something making it work again.

**Comment by reinzor** [comment]
"There is more than one key-value combination in the choices-dictionary";
what does this mean? The definition of a dictionary in Python is values
with unique keys.

Nothing changed on the interpretation side since it's loaded from the same
image snapshot over and over again. So it is not an update issue or
something. If it's a bug, it was there from the start; I will look at this
next Tuesday.


-Rein

**Comment by egeerts** [comment]
This still works (as is done in speech recognition challenge):
spec = "<person>"
choices = {person : ["john", "sjaak", "frits]}

This does not work anymore:
spec = "<greet> <person>"
choices = {person : ["john", "sjaak", "frits],
                 greet: ["hi", "hello"]}

I'll be there as well on Tuesday.

**Comment by reinzor** [comment]
Hmm, weird.

-Rein

**Comment by rokusottervanger** [comment]
Is this still not solved?

**Comment by reinzor** [comment]
We can close this​

-Rein
